using System;
using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Models;
using Beamable.Common;
using Beamable.Common.Api;
using Newtonsoft.Json;
using SuiFederationCommon.Models.Notifications;

namespace Beamable.SuiFederation.Features.Notifications;

public class PlayerNotificationService : IService
{
    private readonly IBeamableRequester _beamableRequester;
    private readonly JsonSerializerSettings _settings;

    public PlayerNotificationService(IBeamableRequester beamableRequester)
    {
        _beamableRequester = beamableRequester;
        _settings = new JsonSerializerSettings
        {
            Converters = { new NotificationConverter() }
        };
    }

    public async Task SendPlayerNotification(long gamerTag, IPlayerNotification payload)
    {
        try
        {
            var message = JsonConvert.SerializeObject(payload, _settings);
            var request = new
            {
                dbid = gamerTag,
                payload = new
                {
                    context = payload.Context,
                    messageFull = message
                }
            };
            await _beamableRequester.Request<CommonResponse>(Method.POST, "/basic/notification/player", JsonConvert.SerializeObject(request), includeAuthHeader: false);
        }
        catch (Exception)
        {
            BeamableLogger.LogWarning($"Unable to send player {gamerTag} notification.");
        }
    }
}