using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Models;
using Beamable.Server;
using Beamable.SuiFederation.Features.Accounts;
using Beamable.SuiFederation.Features.OAuthProvider;
using SuiFederationCommon;
using SuiFederationCommon.Models;

namespace Beamable.SuiFederation.Endpoints;

public class GetFederationInfoEndpoint : IEndpoint
{
    private readonly AccountsService _accountsService;
    private readonly RequestContext _requestContext;
    private readonly OauthProviderService _oauthProviderService;

    public GetFederationInfoEndpoint(AccountsService accountsService, RequestContext requestContext, OauthProviderService oauthProviderService)
    {
        _accountsService = accountsService;
        _requestContext = requestContext;
        _oauthProviderService = oauthProviderService;
    }

    public async Task<GetFederationInfoResponse> Get()
    {
        var gamerTag = _requestContext.UserId;
        var account = await _accountsService.SearchAccount(gamerTag.ToString());
        var playerIdentities = await ResolveExternalIdentity(gamerTag, account);
        return new GetFederationInfoResponse
        {
            gamerTag = gamerTag,
            email = account?.email.GetNonEmptyOrElse(() => ""),
            externalIdentities = playerIdentities
        };
    }

    private async Task<List<PlayerIdentity>> ResolveExternalIdentity(long gamerTag, Account? account)
    {
        if (account is null || account.external.Length == 0)
            return [];

        var identities = new List<PlayerIdentity>();
        foreach (var identity in account.external)
        {
            var oauthRequest = await _oauthProviderService.GetByGamer(gamerTag, identity.providerNamespace);
            var type = identity.providerNamespace switch
            {
                SuiFederationSettings.SuiExternalIdentityName => "slush",
                SuiFederationSettings.SuiEnokiIdentityName => oauthRequest is not null ? oauthRequest.Provider : "",
                _ => "custodial"
            };
            identities.Add(new PlayerIdentity
            {
                microservice = identity.providerService,
                nameSpace = identity.providerNamespace,
                address = identity.userId,
                type = type
            });
        }
        return identities;
    }
}