//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.LiveOpsDemoMS.LiveOpsDemoMS"/> </summary
    public sealed class LiveOpsDemoMSClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public LiveOpsDemoMSClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public LiveOpsDemoMSClient(Beamable.Common.Dependencies.IDependencyProvider provider) : 
                base(provider)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "LiveOpsDemoMS";
            }
        }
        
        /// <summary>
        /// Call the UpgradeItem method on the LiveOpsDemoMS microservice
        /// <see cref="Beamable.LiveOpsDemoMS.LiveOpsDemoMS.UpgradeItem"/>
        /// </summary>
        public Beamable.Common.Promise<bool> UpgradeItem(long gamerTag, long itemInstanceID, System.Collections.Generic.Dictionary<System.String, System.String> properties)
        {
            object raw_gamerTag = gamerTag;
            object raw_itemInstanceID = itemInstanceID;
            object raw_properties = properties;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("gamerTag", raw_gamerTag);
            serializedFields.Add("itemInstanceID", raw_itemInstanceID);
            serializedFields.Add("properties", raw_properties);
            return this.Request<bool>("LiveOpsDemoMS", "UpgradeItem", serializedFields);
        }
        
        /// <summary>
        /// Call the IncrementStat method on the LiveOpsDemoMS microservice
        /// <see cref="Beamable.LiveOpsDemoMS.LiveOpsDemoMS.IncrementStat"/>
        /// </summary>
        public Beamable.Common.Promise<bool> IncrementStat(long gamerTag)
        {
            object raw_gamerTag = gamerTag;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("gamerTag", raw_gamerTag);
            return this.Request<bool>("LiveOpsDemoMS", "IncrementStat", serializedFields);
        }
        
        /// <summary>
        /// Call the GetSampleStat method on the LiveOpsDemoMS microservice
        /// <see cref="Beamable.LiveOpsDemoMS.LiveOpsDemoMS.GetSampleStat"/>
        /// </summary>
        public Beamable.Common.Promise<int> GetSampleStat(long gamerTag)
        {
            object raw_gamerTag = gamerTag;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("gamerTag", raw_gamerTag);
            return this.Request<int>("LiveOpsDemoMS", "GetSampleStat", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersLiveOpsDemoMSClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Int64 : MicroserviceClientDataWrapper<long>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Collections_Generic_Dictionary_System_String_System_String : MicroserviceClientDataWrapper<System.Collections.Generic.Dictionary<System.String, System.String>>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForLiveOpsDemoMSClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute(50, Beamable.Common.Dependencies.RegistrationOrigin.EDITOR | Beamable.Common.Dependencies.RegistrationOrigin.RUNTIME)]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            System.Func<Beamable.Common.Dependencies.IDependencyProvider, LiveOpsDemoMSClient> factory = p => new LiveOpsDemoMSClient(p);
            builder.AddScoped<LiveOpsDemoMSClient>(factory);
        }
        
        public static LiveOpsDemoMSClient LiveOpsDemoMS(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<LiveOpsDemoMSClient>();
        }
    }
}
