//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.SuiFederation.SuiFederation"/> </summary
    public sealed class SuiFederationClient : MicroserviceClient, Beamable.Common.IHaveServiceName, Beamable.Common.ISupportsFederatedInventory<SuiFederationCommon.SuiWeb3Identity>, Beamable.Common.ISupportsFederatedLogin<SuiFederationCommon.SuiWeb3Identity>, Beamable.Common.ISupportsFederatedInventory<SuiFederationCommon.SuiWeb3EnokiIdentity>, Beamable.Common.ISupportsFederatedLogin<SuiFederationCommon.SuiWeb3EnokiIdentity>, Beamable.Common.ISupportsFederatedInventory<SuiFederationCommon.SuiWeb3ExternalIdentity>, Beamable.Common.ISupportsFederatedLogin<SuiFederationCommon.SuiWeb3ExternalIdentity>
    {
        
        public SuiFederationClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public SuiFederationClient(Beamable.Common.Dependencies.IDependencyProvider provider) : 
                base(provider)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "SuiFederation";
            }
        }
        
        /// <summary>
        /// Call the GetRealmAccount method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.GetRealmAccount"/>
        /// </summary>
        public Beamable.Common.Promise<string> GetRealmAccount()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<string>("SuiFederation", "GetRealmAccount", serializedFields);
        }
        
        /// <summary>
        /// Call the GenerateRealmAccount method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.GenerateRealmAccount"/>
        /// </summary>
        public Beamable.Common.Promise<string> GenerateRealmAccount()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<string>("SuiFederation", "GenerateRealmAccount", serializedFields);
        }
        
        /// <summary>
        /// Call the ImportRealmAccount method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.ImportRealmAccount"/>
        /// </summary>
        public Beamable.Common.Promise<string> ImportRealmAccount(string privateKey)
        {
            object raw_privateKey = privateKey;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("privateKey", raw_privateKey);
            return this.Request<string>("SuiFederation", "ImportRealmAccount", serializedFields);
        }
        
        /// <summary>
        /// Call the ImportAccount method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.ImportAccount"/>
        /// </summary>
        public Beamable.Common.Promise<string> ImportAccount(string id, string privateKey)
        {
            object raw_id = id;
            object raw_privateKey = privateKey;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("id", raw_id);
            serializedFields.Add("privateKey", raw_privateKey);
            return this.Request<string>("SuiFederation", "ImportAccount", serializedFields);
        }
        
        /// <summary>
        /// Call the GetAccount method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.GetAccount"/>
        /// </summary>
        public Beamable.Common.Promise<string> GetAccount(string id)
        {
            object raw_id = id;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("id", raw_id);
            return this.Request<string>("SuiFederation", "GetAccount", serializedFields);
        }
        
        /// <summary>
        /// Call the InitializeContentContracts method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.InitializeContentContracts"/>
        /// </summary>
        public Beamable.Common.Promise<string> InitializeContentContracts()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<string>("SuiFederation", "InitializeContentContracts", serializedFields);
        }
        
        /// <summary>
        /// Call the GetSuiEnvironment method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.GetSuiEnvironment"/>
        /// </summary>
        public Beamable.Common.Promise<string> GetSuiEnvironment()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<string>("SuiFederation", "GetSuiEnvironment", serializedFields);
        }
        
        /// <summary>
        /// Call the GetFederationInfo method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.GetFederationInfo"/>
        /// </summary>
        public Beamable.Common.Promise<SuiFederationCommon.Models.GetFederationInfoResponse> GetFederationInfo()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<SuiFederationCommon.Models.GetFederationInfoResponse>("SuiFederation", "GetFederationInfo", serializedFields);
        }
        
        /// <summary>
        /// Call the Withdraw method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.Withdraw"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> Withdraw(string contentId, long amount)
        {
            object raw_contentId = contentId;
            object raw_amount = amount;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("contentId", raw_contentId);
            serializedFields.Add("amount", raw_amount);
            return this.Request<Beamable.Common.Unit>("SuiFederation", "Withdraw", serializedFields);
        }
        
        /// <summary>
        /// Call the OAuthCallback method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.OAuthCallback"/>
        /// </summary>
        public Beamable.Common.Promise<SuiFederationCommon.Models.Oauth.OauthCallbackResponse> OAuthCallback()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<SuiFederationCommon.Models.Oauth.OauthCallbackResponse>("SuiFederation", "OAuthCallback", serializedFields);
        }
        
        /// <summary>
        /// Call the KioskList method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.KioskList"/>
        /// </summary>
        public Beamable.Common.Promise<SuiFederationCommon.Models.Kiosk.KioskListResponse> KioskList()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<SuiFederationCommon.Models.Kiosk.KioskListResponse>("SuiFederation", "KioskList", serializedFields);
        }
        
        /// <summary>
        /// Call the ListForSale method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.ListForSale"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> ListForSale(long itemId, long price, string optionalKioskContentId)
        {
            object raw_itemId = itemId;
            object raw_price = price;
            object raw_optionalKioskContentId = optionalKioskContentId;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("itemId", raw_itemId);
            serializedFields.Add("price", raw_price);
            serializedFields.Add("optionalKioskContentId", raw_optionalKioskContentId);
            return this.Request<Beamable.Common.Unit>("SuiFederation", "ListForSale", serializedFields);
        }
        
        /// <summary>
        /// Call the DelistFromSale method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.DelistFromSale"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> DelistFromSale(string listingId)
        {
            object raw_listingId = listingId;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("listingId", raw_listingId);
            return this.Request<Beamable.Common.Unit>("SuiFederation", "DelistFromSale", serializedFields);
        }
        
        /// <summary>
        /// Call the OwnedListings method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.OwnedListings"/>
        /// </summary>
        public Beamable.Common.Promise<SuiFederationCommon.Models.Kiosk.KioskListingsResponse> OwnedListings(string optionalKioskContentId)
        {
            object raw_optionalKioskContentId = optionalKioskContentId;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("optionalKioskContentId", raw_optionalKioskContentId);
            return this.Request<SuiFederationCommon.Models.Kiosk.KioskListingsResponse>("SuiFederation", "OwnedListings", serializedFields);
        }
        
        /// <summary>
        /// Call the AllListings method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.AllListings"/>
        /// </summary>
        public Beamable.Common.Promise<SuiFederationCommon.Models.Kiosk.KioskListingsResponsePaginated> AllListings(string optionalKioskContentId, int page, int pageSize)
        {
            object raw_optionalKioskContentId = optionalKioskContentId;
            object raw_page = page;
            object raw_pageSize = pageSize;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("optionalKioskContentId", raw_optionalKioskContentId);
            serializedFields.Add("page", raw_page);
            serializedFields.Add("pageSize", raw_pageSize);
            return this.Request<SuiFederationCommon.Models.Kiosk.KioskListingsResponsePaginated>("SuiFederation", "AllListings", serializedFields);
        }
        
        /// <summary>
        /// Call the KioskPurchase method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.KioskPurchase"/>
        /// </summary>
        public Beamable.Common.Promise<SuiFederationCommon.Models.Kiosk.KioskPurchaseResponse> KioskPurchase(string listingId)
        {
            object raw_listingId = listingId;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("listingId", raw_listingId);
            return this.Request<SuiFederationCommon.Models.Kiosk.KioskPurchaseResponse>("SuiFederation", "KioskPurchase", serializedFields);
        }
        
        /// <summary>
        /// Call the PersonalKioskCreate method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.PersonalKioskCreate"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> PersonalKioskCreate()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<Beamable.Common.Unit>("SuiFederation", "PersonalKioskCreate", serializedFields);
        }
        
        /// <summary>
        /// Call the PersonalKioskList method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.PersonalKioskList"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> PersonalKioskList(long itemId, long price, long exclusiveBuyer)
        {
            object raw_itemId = itemId;
            object raw_price = price;
            object raw_exclusiveBuyer = exclusiveBuyer;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("itemId", raw_itemId);
            serializedFields.Add("price", raw_price);
            serializedFields.Add("exclusiveBuyer", raw_exclusiveBuyer);
            return this.Request<Beamable.Common.Unit>("SuiFederation", "PersonalKioskList", serializedFields);
        }
        
        /// <summary>
        /// Call the PersonalKioskDelist method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.PersonalKioskDelist"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> PersonalKioskDelist(string listingId, bool remove)
        {
            object raw_listingId = listingId;
            object raw_remove = remove;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("listingId", raw_listingId);
            serializedFields.Add("remove", raw_remove);
            return this.Request<Beamable.Common.Unit>("SuiFederation", "PersonalKioskDelist", serializedFields);
        }
        
        /// <summary>
        /// Call the PersonalKioskTake method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.PersonalKioskTake"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> PersonalKioskTake(string listingId)
        {
            object raw_listingId = listingId;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("listingId", raw_listingId);
            return this.Request<Beamable.Common.Unit>("SuiFederation", "PersonalKioskTake", serializedFields);
        }
        
        /// <summary>
        /// Call the PersonalKioskDeclinePurchase method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.PersonalKioskDeclinePurchase"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> PersonalKioskDeclinePurchase(string listingId)
        {
            object raw_listingId = listingId;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("listingId", raw_listingId);
            return this.Request<Beamable.Common.Unit>("SuiFederation", "PersonalKioskDeclinePurchase", serializedFields);
        }
        
        /// <summary>
        /// Call the PersonalKioskCancelExclusive method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.PersonalKioskCancelExclusive"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> PersonalKioskCancelExclusive(string listingId)
        {
            object raw_listingId = listingId;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("listingId", raw_listingId);
            return this.Request<Beamable.Common.Unit>("SuiFederation", "PersonalKioskCancelExclusive", serializedFields);
        }
        
        /// <summary>
        /// Call the PersonalKioskPurchase method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.PersonalKioskPurchase"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> PersonalKioskPurchase(string listingId)
        {
            object raw_listingId = listingId;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("listingId", raw_listingId);
            return this.Request<Beamable.Common.Unit>("SuiFederation", "PersonalKioskPurchase", serializedFields);
        }
        
        /// <summary>
        /// Call the PersonalKioskWithDraw method on the SuiFederation microservice
        /// <see cref="Beamable.SuiFederation.SuiFederation.PersonalKioskWithDraw"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> PersonalKioskWithDraw(long amount)
        {
            object raw_amount = amount;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("amount", raw_amount);
            return this.Request<Beamable.Common.Unit>("SuiFederation", "PersonalKioskWithDraw", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersSuiFederationClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Int64 : MicroserviceClientDataWrapper<long>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Int32 : MicroserviceClientDataWrapper<int>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Boolean : MicroserviceClientDataWrapper<bool>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForSuiFederationClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute(50, Beamable.Common.Dependencies.RegistrationOrigin.EDITOR | Beamable.Common.Dependencies.RegistrationOrigin.RUNTIME)]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            System.Func<Beamable.Common.Dependencies.IDependencyProvider, SuiFederationClient> factory = p => new SuiFederationClient(p);
            builder.AddScoped<SuiFederationClient>(factory);
        }
        
        public static SuiFederationClient SuiFederation(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<SuiFederationClient>();
        }
    }
}
