using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Inventory;
using Beamable.Common.Inventory;
using Beamable.Server;
using Beamable.Server.Content;
using Beamable.SuiFederation.Extensions;
using Beamable.SuiFederation.Features.Accounts;
using Beamable.SuiFederation.Features.ChannelProcessor;
using Beamable.SuiFederation.Features.Contract;
using Beamable.SuiFederation.Features.Contract.Storage.Models;
using Beamable.SuiFederation.Features.Inventory;
using Beamable.SuiFederation.Features.Kiosk;
using Beamable.SuiFederation.Features.Kiosk.Exceptions;
using Beamable.SuiFederation.Features.Kiosk.Models;
using Beamable.SuiFederation.Features.Kiosk.Storage;
using Beamable.SuiFederation.Features.Kiosk.Storage.Models;
using Beamable.SuiFederation.Features.Transactions;
using SuiFederationCommon.Extensions;
using SuiFederationCommon.Models.Notifications;

namespace Beamable.SuiFederation.Endpoints.Kiosk;

public class KioskDelistEndpoint : IEndpoint
{
    private readonly RequestContext _requestContext;
    private readonly ContractService _contractService;
    private readonly ContentService _contentService;
    private readonly TransactionManager _transactionManager;
    private readonly AccountsService _accountsService;
    private readonly KioskHandlerFactory _kioskHandlerFactory;
    private readonly UpdatePlayerStateService _updatePlayerStateService;
    private readonly GetInventoryStateEndpoint _getInventoryStateEndpoint;
    private readonly KioskListingCollection _kioskListingCollection;

    public KioskDelistEndpoint(RequestContext requestContext, ContractService contractService, ContentService contentService, TransactionManager transactionManager, AccountsService accountsService, KioskHandlerFactory kioskHandlerFactory, UpdatePlayerStateService updatePlayerStateService, GetInventoryStateEndpoint getInventoryStateEndpoint, KioskListingCollection kioskListingCollection)
    {
        _requestContext = requestContext;
        _contractService = contractService;
        _contentService = contentService;
        _transactionManager = transactionManager;
        _accountsService = accountsService;
        _kioskHandlerFactory = kioskHandlerFactory;
        _updatePlayerStateService = updatePlayerStateService;
        _getInventoryStateEndpoint = getInventoryStateEndpoint;
        _kioskListingCollection = kioskListingCollection;
    }

    public async Task DelistFromSale(string listingId)
    {
        var listing = await _kioskListingCollection.GetByListingId(listingId);
        var validateResult = await ValidateRequest(listing);
        var wallet = await _accountsService.GetWallet(_requestContext.UserId, validateResult.Identity);

        var kioskContract = await _contractService.GetKioskContract(listing.ItemContentId.ToContentType(), listing.PriceContentId);

        var handler = _kioskHandlerFactory.GetHandler(validateResult.Identity);
        var kioskTransactionId = new KioskTransactionId();
        var transactionId = await _transactionManager.StartTransaction(wallet, nameof(DelistFromSale), kioskTransactionId, new {listing.ItemContentId, listing.ItemProxyId, listing.ListingId});
        _transactionManager.SetCurrentTransactionContext(transactionId);
        _ = _transactionManager.RunAsyncBlock(transactionId, kioskTransactionId, async () =>
        {
            await ChannelService.Enqueue(_requestContext.UserId, async (_) =>
                await handler.DelistFromSale(new KioskDelistModel(_requestContext.UserId, wallet, listing.ListingId, kioskContract, transactionId.ToString()))
            );

            await ChannelService.Enqueue(_requestContext.UserId, async (_) =>
                await _updatePlayerStateService.Update(new KioskNotification
                {
                    Id = kioskTransactionId
                }, _getInventoryStateEndpoint, validateResult.Identity)
            );
        });
    }

    private async Task<ValidationResult> ValidateRequest(KioskListing listing)
    {
        var itemContentData = await _contentService.GetContent(listing.ItemContentId);
        if (itemContentData is not ItemContent itemContent)
            throw new KioskException($"Item content id {listing.ItemContentId} is not a valid item.");

        if (listing.Status != KioskListingStatus.Active)
            throw new KioskException($"Item with inventory ID {listing.ItemInventoryId} is not actively listed on the kiosk.");

        if (!itemContent.federation.HasValue)
            throw new KioskException($"Item content id {listing.ItemContentId} is not federated.");
        return new ValidationResult(new MicroserviceInfo(itemContent.federation.Value.Service, itemContent.federation.Value.Namespace));
    }

    private readonly record struct ValidationResult(MicroserviceInfo Identity);
}