using System.Linq;
using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Inventory;
using Beamable.Api.Autogenerated.Models;
using Beamable.Server;
using Beamable.Server.Content;
using Beamable.SuiFederation.Extensions;
using Beamable.SuiFederation.Features.Accounts;
using Beamable.SuiFederation.Features.ChannelProcessor;
using Beamable.SuiFederation.Features.Contract;
using Beamable.SuiFederation.Features.Contract.Handlers;
using Beamable.SuiFederation.Features.Contract.Storage.Models;
using Beamable.SuiFederation.Features.Inventory;
using Beamable.SuiFederation.Features.Kiosk;
using Beamable.SuiFederation.Features.Kiosk.Exceptions;
using Beamable.SuiFederation.Features.Kiosk.Models;
using Beamable.SuiFederation.Features.Kiosk.Storage;
using Beamable.SuiFederation.Features.Kiosk.Storage.Models;
using Beamable.SuiFederation.Features.Transactions;
using SuiFederationCommon;
using SuiFederationCommon.Extensions;
using SuiFederationCommon.Models.Notifications;

namespace Beamable.SuiFederation.Endpoints.Kiosk;

public class PersonalKioskPurchaseEndpoint : IEndpoint
{
    private readonly RequestContext _requestContext;
    private readonly ContractService _contractService;
    private readonly InventoryApi _inventoryApi;
    private readonly TransactionManager _transactionManager;
    private readonly AccountsService _accountsService;
    private readonly KioskService _kioskService;
    private readonly UpdatePlayerStateService _updatePlayerStateService;
    private readonly GetInventoryStateEndpoint _getInventoryStateEndpoint;
    private readonly PersonalKioskCollection _personalKioskCollection;
    private readonly KioskListingCollection _kioskListingCollection;

    public PersonalKioskPurchaseEndpoint(RequestContext requestContext, ContractService contractService, InventoryApi inventoryApi, TransactionManager transactionManager, AccountsService accountsService, KioskService kioskService, UpdatePlayerStateService updatePlayerStateService, GetInventoryStateEndpoint getInventoryStateEndpoint, PersonalKioskCollection personalKioskCollection, KioskListingCollection kioskListingCollection)
    {
        _requestContext = requestContext;
        _contractService = contractService;
        _inventoryApi = inventoryApi;
        _transactionManager = transactionManager;
        _accountsService = accountsService;
        _kioskService = kioskService;
        _updatePlayerStateService = updatePlayerStateService;
        _getInventoryStateEndpoint = getInventoryStateEndpoint;
        _personalKioskCollection = personalKioskCollection;
        _kioskListingCollection = kioskListingCollection;
    }

    public async Task PersonalKioskPurchase(string listingId)
    {
        var validateResult = await ValidateRequest(_requestContext.UserId, listingId);
        var wallet = await _accountsService.GetWallet(_requestContext.UserId, validateResult.Identity);
        var itemContract = await _contractService.GetByContentId<NftContract>(validateResult.ItemContentId.ToContentType());
        var kioskContract = await _contractService.GetByContentId<PlayerKioskContract>(PlayerKioskHandler.ModuleName);

        var kioskTransactionId = new KioskTransactionId();
        var transactionId = await _transactionManager.StartTransaction(wallet, nameof(PersonalKioskPurchase), kioskTransactionId, new {wallet, listingId});
        _transactionManager.SetCurrentTransactionContext(transactionId);
        _ = _transactionManager.RunAsyncBlock(transactionId, kioskTransactionId, async () =>
        {
            await ChannelService.Enqueue(_requestContext.UserId, async (_) =>
                await _kioskService.PersonalKioskPurchase(new PersonalKioskPurchaseModel(_requestContext.UserId, wallet, itemContract, validateResult.BuyerPersonalKiosk, validateResult.SellerPersonalKiosk, kioskContract, validateResult.ItemProxyId, validateResult.Price, transactionId.ToString(), validateResult.Identity.MicroserviceNamespace, listingId, validateResult.PurchaseCap))
            );

            await ChannelService.Enqueue(_requestContext.UserId, async (_) =>
                await _updatePlayerStateService.Update(new KioskNotification
                {
                    Id = kioskTransactionId
                }, _getInventoryStateEndpoint, validateResult.Identity)
            );
        });
    }

    private async Task<ValidationResult> ValidateRequest(long gamerTag, string listingId)
    {
        var listing = await _kioskListingCollection.GetByListingId(listingId);
        var buyerPersonalKiosk = await _personalKioskCollection.GetByPlayer(gamerTag);
        if (buyerPersonalKiosk is null)
            throw new KioskException($"Player {gamerTag} does not have a personal kiosk.");

        var sellerPersonalKiosk = await _personalKioskCollection.GetByPlayer(listing.GamerTag);
        if (sellerPersonalKiosk is null)
            throw new KioskException($"Player {gamerTag} does not have a personal kiosk.");

        if (listing.Status != KioskListingStatus.Active)
            throw new KioskException($"Item with inventory ID {listing.ItemInventoryId} is not actively listed on the kiosk.");

        var maybePurchaseCap = "";
        if (listing.ExclusiveBuyer is not null && listing.ExclusiveBuyer.GamerTag == gamerTag)
        {
            maybePurchaseCap = listing.ExclusiveBuyer.PurchaseCap;
        }

        return new ValidationResult(listing.ItemContentId, listing.ItemProxyId, listing.Price, buyerPersonalKiosk, sellerPersonalKiosk, new MicroserviceInfo(SuiFederationSettings.MicroserviceName, listing.Namespace), maybePurchaseCap);
    }

    private readonly record struct ValidationResult(string ItemContentId, string ItemProxyId, long Price, PersonalKiosk BuyerPersonalKiosk, PersonalKiosk SellerPersonalKiosk, MicroserviceInfo Identity, string PurchaseCap);
}