using System.Linq;
using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Inventory;
using Beamable.Api.Autogenerated.Models;
using Beamable.Server;
using Beamable.Server.Content;
using Beamable.SuiFederation.Extensions;
using Beamable.SuiFederation.Features.Accounts;
using Beamable.SuiFederation.Features.ChannelProcessor;
using Beamable.SuiFederation.Features.Contract;
using Beamable.SuiFederation.Features.Contract.Handlers;
using Beamable.SuiFederation.Features.Contract.Storage.Models;
using Beamable.SuiFederation.Features.Inventory;
using Beamable.SuiFederation.Features.Kiosk;
using Beamable.SuiFederation.Features.Kiosk.Exceptions;
using Beamable.SuiFederation.Features.Kiosk.Models;
using Beamable.SuiFederation.Features.Kiosk.Storage;
using Beamable.SuiFederation.Features.Kiosk.Storage.Models;
using Beamable.SuiFederation.Features.Transactions;
using SuiFederationCommon.Extensions;
using SuiFederationCommon.Models.Notifications;

namespace Beamable.SuiFederation.Endpoints.Kiosk;

public class PersonalKioskListEndpoint : IEndpoint
{
    private readonly RequestContext _requestContext;
    private readonly ContractService _contractService;
    private readonly InventoryApi _inventoryApi;
    private readonly ContentService _contentService;
    private readonly TransactionManager _transactionManager;
    private readonly AccountsService _accountsService;
    private readonly KioskService _kioskService;
    private readonly UpdatePlayerStateService _updatePlayerStateService;
    private readonly GetInventoryStateEndpoint _getInventoryStateEndpoint;
    private readonly PersonalKioskCollection _personalKioskCollection;

    public PersonalKioskListEndpoint(RequestContext requestContext, ContractService contractService, InventoryApi inventoryApi, ContentService contentService, TransactionManager transactionManager, AccountsService accountsService, UpdatePlayerStateService updatePlayerStateService, GetInventoryStateEndpoint getInventoryStateEndpoint, KioskService kioskService, PersonalKioskCollection personalKioskCollection)
    {
        _requestContext = requestContext;
        _contractService = contractService;
        _inventoryApi = inventoryApi;
        _contentService = contentService;
        _transactionManager = transactionManager;
        _accountsService = accountsService;
        _updatePlayerStateService = updatePlayerStateService;
        _getInventoryStateEndpoint = getInventoryStateEndpoint;
        _kioskService = kioskService;
        _personalKioskCollection = personalKioskCollection;
    }

    public async Task PersonalKioskList(long itemId, long price, long exclusiveBuyer)
    {
        var items = await _inventoryApi.ObjectGet(_requestContext.UserId);
        var validationResult = await ValidateRequest(_requestContext.UserId, itemId, price, items);
        var wallet = await _accountsService.GetWallet(_requestContext.UserId, validationResult.Identity);
        var buyerWallet = exclusiveBuyer != 0 ? await _accountsService.GetWallet(exclusiveBuyer, validationResult.Identity) : "";
        var itemContract = await _contractService.GetByContentId<NftContract>(validationResult.ItemContentId.ToContentType());
        var kioskContract = await _contractService.GetByContentId<PlayerKioskContract>(PlayerKioskHandler.ModuleName);

        var kioskTransactionId = new KioskTransactionId();
        var transactionId = await _transactionManager.StartTransaction(wallet, nameof(PersonalKioskList), kioskTransactionId, new {wallet, itemId, price, buyerWallet});
        _transactionManager.SetCurrentTransactionContext(transactionId);
        _ = _transactionManager.RunAsyncBlock(transactionId, kioskTransactionId, async () =>
        {
            await ChannelService.Enqueue(_requestContext.UserId, async (_) =>
                await _kioskService.PersonalKioskList(new PersonalKioskListModel(_requestContext.UserId, wallet, validationResult.ItemContentId, itemId, itemContract, validationResult.PersonalKiosk, kioskContract, validationResult.ItemProxyId, price, transactionId.ToString(), validationResult.Identity.MicroserviceNamespace, exclusiveBuyer, buyerWallet))
            );

            await ChannelService.Enqueue(_requestContext.UserId, async (_) =>
                await _updatePlayerStateService.Update(new KioskNotification
                {
                    Id = kioskTransactionId
                }, _getInventoryStateEndpoint, validationResult.Identity)
            );
        });
    }

    private async Task<ValidationResult> ValidateRequest(long gamerTag, long itemId, long price, InventoryView items)
    {
        if (price <= 0)
            throw new KioskException("Price must be greater than zero.");

        var itemResult = items.items
            .SelectMany(g => g.items, (g, i) => new { GroupId = g.id, Item = i, Proxy = i.proxy.Value })
            .FirstOrDefault(x => x.Item.id == itemId && x.Item.proxy.HasValue);
        if (itemResult is null)
            throw new KioskException($"Item with id {itemId} does not exist in the inventory.");

        var personalKiosk = await _personalKioskCollection.GetByPlayer(gamerTag);
        if (personalKiosk is null)
            throw new KioskException($"Player {gamerTag} does not have a personal kiosk.");

        return new ValidationResult(itemResult.GroupId, itemResult.Item.proxyId.Value, personalKiosk, new MicroserviceInfo(itemResult.Proxy.service, itemResult.Proxy.namespaceKey));
    }

    private readonly record struct ValidationResult(string ItemContentId, string ItemProxyId, PersonalKiosk PersonalKiosk, MicroserviceInfo Identity);
}