using System.Linq;
using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Inventory;
using Beamable.Api.Autogenerated.Models;
using Beamable.Server;
using Beamable.Server.Content;
using Beamable.SuiFederation.Extensions;
using Beamable.SuiFederation.Features.Accounts;
using Beamable.SuiFederation.Features.ChannelProcessor;
using Beamable.SuiFederation.Features.Contract;
using Beamable.SuiFederation.Features.Contract.Handlers;
using Beamable.SuiFederation.Features.Contract.Storage.Models;
using Beamable.SuiFederation.Features.Inventory;
using Beamable.SuiFederation.Features.Kiosk;
using Beamable.SuiFederation.Features.Kiosk.Exceptions;
using Beamable.SuiFederation.Features.Kiosk.Models;
using Beamable.SuiFederation.Features.Kiosk.Storage;
using Beamable.SuiFederation.Features.Kiosk.Storage.Models;
using Beamable.SuiFederation.Features.Transactions;
using SuiFederationCommon;
using SuiFederationCommon.Extensions;
using SuiFederationCommon.Models.Notifications;

namespace Beamable.SuiFederation.Endpoints.Kiosk;

public class PersonalKioskWithdrawEndpoint : IEndpoint
{
    private readonly RequestContext _requestContext;
    private readonly ContractService _contractService;
    private readonly InventoryApi _inventoryApi;
    private readonly ContentService _contentService;
    private readonly TransactionManager _transactionManager;
    private readonly AccountsService _accountsService;
    private readonly KioskService _kioskService;
    private readonly UpdatePlayerStateService _updatePlayerStateService;
    private readonly GetInventoryStateEndpoint _getInventoryStateEndpoint;
    private readonly PersonalKioskCollection _personalKioskCollection;

    public PersonalKioskWithdrawEndpoint(RequestContext requestContext, ContractService contractService, InventoryApi inventoryApi, ContentService contentService, TransactionManager transactionManager, AccountsService accountsService, KioskService kioskService, UpdatePlayerStateService updatePlayerStateService, GetInventoryStateEndpoint getInventoryStateEndpoint, PersonalKioskCollection personalKioskCollection)
    {
        _requestContext = requestContext;
        _contractService = contractService;
        _inventoryApi = inventoryApi;
        _contentService = contentService;
        _transactionManager = transactionManager;
        _accountsService = accountsService;
        _kioskService = kioskService;
        _updatePlayerStateService = updatePlayerStateService;
        _getInventoryStateEndpoint = getInventoryStateEndpoint;
        _personalKioskCollection = personalKioskCollection;
    }

    public async Task PersonalKioskWithdraw(long amount)
    {
        var identity =
            new MicroserviceInfo(SuiFederationSettings.MicroserviceName, SuiFederationSettings.SuiIdentityName);
        var wallet = await _accountsService.GetWallet(_requestContext.UserId, identity);
        var kioskContract = await _contractService.GetByContentId<PlayerKioskContract>(PlayerKioskHandler.ModuleName);
        var personalKiosk = await _personalKioskCollection.GetByPlayer(_requestContext.UserId);
        if (personalKiosk is null)
            throw new KioskException($"Player {_requestContext.UserId} does not have a personal kiosk.");

        var kioskTransactionId = new KioskTransactionId();
        var transactionId = await _transactionManager.StartTransaction(wallet, nameof(PersonalKioskWithdraw), kioskTransactionId, new {wallet, amount});
        _transactionManager.SetCurrentTransactionContext(transactionId);
        _ = _transactionManager.RunAsyncBlock(transactionId, kioskTransactionId, async () =>
        {
            await ChannelService.Enqueue(_requestContext.UserId, async (_) =>
                await _kioskService.PersonalKioskWithdraw(new PersonalKioskWithdrawModel(_requestContext.UserId, wallet, personalKiosk, kioskContract, amount, transactionId.ToString(), identity.MicroserviceNamespace))
            );

            await ChannelService.Enqueue(_requestContext.UserId, async (_) =>
                await _updatePlayerStateService.Update(new KioskNotification
                {
                    Id = kioskTransactionId
                }, _getInventoryStateEndpoint, identity)
            );
        });
    }
}