using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Inventory;
using Beamable.Server;
using Beamable.SuiFederation.Extensions;
using Beamable.SuiFederation.Features.Accounts;
using Beamable.SuiFederation.Features.ChannelProcessor;
using Beamable.SuiFederation.Features.Contract;
using Beamable.SuiFederation.Features.Contract.Handlers;
using Beamable.SuiFederation.Features.Contract.Storage.Models;
using Beamable.SuiFederation.Features.Inventory;
using Beamable.SuiFederation.Features.Kiosk;
using Beamable.SuiFederation.Features.Kiosk.Exceptions;
using Beamable.SuiFederation.Features.Kiosk.Models;
using Beamable.SuiFederation.Features.Kiosk.Storage;
using Beamable.SuiFederation.Features.Transactions;
using SuiFederationCommon;
using SuiFederationCommon.Models.Notifications;

namespace Beamable.SuiFederation.Endpoints.Kiosk;

public class PersonalKioskCreateEndpoint : IEndpoint
{
    private readonly RequestContext _requestContext;
    private readonly TransactionManager _transactionManager;
    private readonly AccountsService _accountsService;
    private readonly UpdatePlayerStateService _updatePlayerStateService;
    private readonly GetInventoryStateEndpoint _getInventoryStateEndpoint;
    private readonly KioskService _kioskService;
    private readonly ContractService _contractService;
    private readonly PersonalKioskCollection _personalKioskCollection;

    public PersonalKioskCreateEndpoint(RequestContext requestContext, TransactionManager transactionManager, AccountsService accountsService, UpdatePlayerStateService updatePlayerStateService, GetInventoryStateEndpoint getInventoryStateEndpoint, KioskService kioskService, ContractService contractService, PersonalKioskCollection personalKioskCollection)
    {
        _requestContext = requestContext;
        _transactionManager = transactionManager;
        _accountsService = accountsService;
        _updatePlayerStateService = updatePlayerStateService;
        _getInventoryStateEndpoint = getInventoryStateEndpoint;
        _kioskService = kioskService;
        _contractService = contractService;
        _personalKioskCollection = personalKioskCollection;
    }

    public async Task PersonalKioskCreate()
    {
        var existingKiosk = await _personalKioskCollection.GetByPlayer(_requestContext.UserId);
        if (existingKiosk is not null) return;

        var identity = new MicroserviceInfo(SuiFederationSettings.MicroserviceName, SuiFederationSettings.SuiIdentityName);
        var wallet = await _accountsService.GetWallet(_requestContext.UserId, identity);
        var contract = await _contractService.GetByContentId<PlayerKioskContract>(PlayerKioskHandler.ModuleName);
        var kioskTransactionId = new KioskTransactionId();
        var transactionId = await _transactionManager.StartTransaction(wallet, nameof(PersonalKioskCreate), kioskTransactionId, new {wallet});
        _transactionManager.SetCurrentTransactionContext(transactionId);
        _ = _transactionManager.RunAsyncBlock(transactionId, kioskTransactionId, async () =>
        {
            await ChannelService.Enqueue(_requestContext.UserId, async (_) =>
                await _kioskService.CreatePersonalKiosk(new PersonalKioskCreateModel(_requestContext.UserId, wallet, contract, transactionId.ToString(), identity.MicroserviceNamespace))
            );

            await ChannelService.Enqueue(_requestContext.UserId, async (_) =>
                await _updatePlayerStateService.Update(new KioskNotification
                {
                    Id = kioskTransactionId
                }, _getInventoryStateEndpoint, identity)
            );
        });
    }
}