using System.Linq;
using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Inventory;
using Beamable.Api.Autogenerated.Models;
using Beamable.Server;
using Beamable.Server.Content;
using Beamable.SuiFederation.Extensions;
using Beamable.SuiFederation.Features.Accounts;
using Beamable.SuiFederation.Features.ChannelProcessor;
using Beamable.SuiFederation.Features.Contract;
using Beamable.SuiFederation.Features.Contract.Handlers;
using Beamable.SuiFederation.Features.Contract.Storage.Models;
using Beamable.SuiFederation.Features.Inventory;
using Beamable.SuiFederation.Features.Kiosk;
using Beamable.SuiFederation.Features.Kiosk.Exceptions;
using Beamable.SuiFederation.Features.Kiosk.Models;
using Beamable.SuiFederation.Features.Kiosk.Storage;
using Beamable.SuiFederation.Features.Kiosk.Storage.Models;
using Beamable.SuiFederation.Features.Transactions;
using SuiFederationCommon;
using SuiFederationCommon.Extensions;
using SuiFederationCommon.Models.Notifications;

namespace Beamable.SuiFederation.Endpoints.Kiosk;

public class PersonalKioskCancelExclusiveEndpoint : IEndpoint
{
    private readonly RequestContext _requestContext;
    private readonly ContractService _contractService;
    private readonly InventoryApi _inventoryApi;
    private readonly ContentService _contentService;
    private readonly TransactionManager _transactionManager;
    private readonly AccountsService _accountsService;
    private readonly KioskService _kioskService;
    private readonly UpdatePlayerStateService _updatePlayerStateService;
    private readonly GetInventoryStateEndpoint _getInventoryStateEndpoint;
    private readonly PersonalKioskCollection _personalKioskCollection;
    private readonly KioskListingCollection _kioskListingCollection;

    public PersonalKioskCancelExclusiveEndpoint(RequestContext requestContext, ContractService contractService, InventoryApi inventoryApi, ContentService contentService, TransactionManager transactionManager, AccountsService accountsService, KioskService kioskService, UpdatePlayerStateService updatePlayerStateService, GetInventoryStateEndpoint getInventoryStateEndpoint, PersonalKioskCollection personalKioskCollection, KioskListingCollection kioskListingCollection)
    {
        _requestContext = requestContext;
        _contractService = contractService;
        _inventoryApi = inventoryApi;
        _contentService = contentService;
        _transactionManager = transactionManager;
        _accountsService = accountsService;
        _kioskService = kioskService;
        _updatePlayerStateService = updatePlayerStateService;
        _getInventoryStateEndpoint = getInventoryStateEndpoint;
        _personalKioskCollection = personalKioskCollection;
        _kioskListingCollection = kioskListingCollection;
    }
    public async Task PersonalKioskCancelExclusive(string listingId)
    {
        var validationResult = await ValidateRequest(_requestContext.UserId, listingId);
        var wallet = await _accountsService.GetWallet(_requestContext.UserId, validationResult.Identity);
        var itemContract = await _contractService.GetByContentId<NftContract>(validationResult.ItemContentId.ToContentType());
        var kioskContract = await _contractService.GetByContentId<PlayerKioskContract>(PlayerKioskHandler.ModuleName);
        var kioskTransactionId = new KioskTransactionId();
        var transactionId = await _transactionManager.StartTransaction(wallet, nameof(PersonalKioskCancelExclusive), kioskTransactionId, new {wallet, listingId});
        _transactionManager.SetCurrentTransactionContext(transactionId);
        _ = _transactionManager.RunAsyncBlock(transactionId, kioskTransactionId, async () =>
        {
            await ChannelService.Enqueue(_requestContext.UserId, async (_) =>
                await _kioskService.PersonalKioskCancelExclusive(new PersonalKioskCancelExclusiveModel(_requestContext.UserId, listingId, wallet, validationResult.PersonalKiosk, itemContract, kioskContract, validationResult.Seller, validationResult.PurchaseCap, transactionId.ToString(), validationResult.Identity.MicroserviceNamespace))
            );

            await ChannelService.Enqueue(_requestContext.UserId, async (_) =>
                await _updatePlayerStateService.Update(new KioskNotification
                {
                    Id = kioskTransactionId
                }, _getInventoryStateEndpoint, validationResult.Identity)
            );
        });
    }

    private async Task<ValidationResult> ValidateRequest(long gamerTag, string listingId)
    {
        var listing = await _kioskListingCollection.GetByListingId(listingId);

        var personalKiosk = await _personalKioskCollection.GetByPlayer(gamerTag);
        if (personalKiosk is null)
            throw new KioskException($"Player {gamerTag} does not have a personal kiosk.");

        if (listing.ExclusiveBuyer is null)
            throw new KioskException($"Listing {listingId} is not exclusive.");

        return new ValidationResult(listing.ItemContentId, personalKiosk, listing.ExclusiveBuyer.PurchaseCap, listing.Wallet, new MicroserviceInfo(SuiFederationSettings.MicroserviceName, listing.Namespace));
    }

    private readonly record struct ValidationResult(string ItemContentId, PersonalKiosk PersonalKiosk, string PurchaseCap, string Seller, MicroserviceInfo Identity);
}