using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Inventory;
using Beamable.Server;
using Beamable.Server.Content;
using Beamable.SuiFederation.Extensions;
using Beamable.SuiFederation.Features.Accounts;
using Beamable.SuiFederation.Features.ChannelProcessor;
using Beamable.SuiFederation.Features.Contract;
using Beamable.SuiFederation.Features.Contract.Handlers;
using Beamable.SuiFederation.Features.Contract.Storage.Models;
using Beamable.SuiFederation.Features.Inventory;
using Beamable.SuiFederation.Features.Kiosk;
using Beamable.SuiFederation.Features.Kiosk.Exceptions;
using Beamable.SuiFederation.Features.Kiosk.Models;
using Beamable.SuiFederation.Features.Kiosk.Storage;
using Beamable.SuiFederation.Features.Kiosk.Storage.Models;
using Beamable.SuiFederation.Features.Transactions;
using SuiFederationCommon;
using SuiFederationCommon.Extensions;
using SuiFederationCommon.Models.Notifications;

namespace Beamable.SuiFederation.Endpoints.Kiosk;

public class PersonalKioskDelistEndpoint : IEndpoint
{
    private readonly RequestContext _requestContext;
    private readonly ContractService _contractService;
    private readonly TransactionManager _transactionManager;
    private readonly AccountsService _accountsService;
    private readonly KioskService _kioskService;
    private readonly UpdatePlayerStateService _updatePlayerStateService;
    private readonly GetInventoryStateEndpoint _getInventoryStateEndpoint;
    private readonly PersonalKioskCollection _personalKioskCollection;
    private readonly KioskListingCollection _kioskListingCollection;

    public PersonalKioskDelistEndpoint(RequestContext requestContext, ContractService contractService, TransactionManager transactionManager, AccountsService accountsService, UpdatePlayerStateService updatePlayerStateService, GetInventoryStateEndpoint getInventoryStateEndpoint, KioskService kioskService, PersonalKioskCollection personalKioskCollection, KioskListingCollection kioskListingCollection)
    {
        _requestContext = requestContext;
        _contractService = contractService;
        _transactionManager = transactionManager;
        _accountsService = accountsService;
        _updatePlayerStateService = updatePlayerStateService;
        _getInventoryStateEndpoint = getInventoryStateEndpoint;
        _kioskService = kioskService;
        _personalKioskCollection = personalKioskCollection;
        _kioskListingCollection = kioskListingCollection;
    }

    public async Task PersonalKioskDelist(string listingId, bool remove)
    {
        var validationResult = await ValidateRequest(_requestContext.UserId, listingId);
        var wallet = await _accountsService.GetWallet(_requestContext.UserId, validationResult.Identity);
        var itemContract = await _contractService.GetByContentId<NftContract>(validationResult.ItemContentId.ToContentType());
        var kioskContract = await _contractService.GetByContentId<PlayerKioskContract>(PlayerKioskHandler.ModuleName);

        var kioskTransactionId = new KioskTransactionId();
        var transactionId = await _transactionManager.StartTransaction(wallet, nameof(PersonalKioskDelist), kioskTransactionId, new {wallet, listingId, remove});
        _transactionManager.SetCurrentTransactionContext(transactionId);
        _ = _transactionManager.RunAsyncBlock(transactionId, kioskTransactionId, async () =>
        {
            await ChannelService.Enqueue(_requestContext.UserId, async (_) =>
                await _kioskService.PersonalKioskDelist(new PersonalKioskDelistModel(_requestContext.UserId, wallet, itemContract, validationResult.PersonalKiosk, kioskContract, validationResult.ItemProxyId, transactionId.ToString(), validationResult.Identity.MicroserviceNamespace, remove))
            );

            await ChannelService.Enqueue(_requestContext.UserId, async (_) =>
                await _updatePlayerStateService.Update(new KioskNotification
                {
                    Id = kioskTransactionId
                }, _getInventoryStateEndpoint, validationResult.Identity)
            );
        });
    }

    private async Task<ValidationResult> ValidateRequest(long gamerTag, string listingId)
    {
        var listing = await _kioskListingCollection.GetByListingId(listingId);

        var personalKiosk = await _personalKioskCollection.GetByPlayer(gamerTag);
        if (personalKiosk is null)
            throw new KioskException($"Player {gamerTag} does not have a personal kiosk.");

        return new ValidationResult(listing.ItemContentId, listing.ItemProxyId, personalKiosk, new MicroserviceInfo(SuiFederationSettings.MicroserviceName, listing.Namespace));
    }

    private readonly record struct ValidationResult(string ItemContentId, string ItemProxyId, PersonalKiosk PersonalKiosk, MicroserviceInfo Identity);
}